import { ChecklistGroup } from './system-design-checklist';

const G = (title: string, items: { id: number; text: string; depth: number; checked: boolean }[]): ChecklistGroup => ({ title, items });

const groups: ChecklistGroup[] = [
  G('Week 1 — OOP Fundamentals + SOLID', [
    { id: 3001, text: 'Abstraction', depth: 0, checked: false },
    { id: 3002, text: 'Abstract classes', depth: 1, checked: false },
    { id: 3003, text: 'Interfaces', depth: 1, checked: false },
    { id: 3004, text: 'Implement abstraction from scratch in Java', depth: 1, checked: false },
    { id: 3005, text: 'Encapsulation', depth: 0, checked: false },
    { id: 3006, text: 'Access modifiers', depth: 1, checked: false },
    { id: 3007, text: 'Data hiding', depth: 1, checked: false },
    { id: 3008, text: 'Implement encapsulation from scratch in Java', depth: 1, checked: false },
    { id: 3009, text: 'Inheritance', depth: 0, checked: false },
    { id: 3010, text: 'Types of inheritance in Java', depth: 1, checked: false },
    { id: 3011, text: 'Method overriding', depth: 1, checked: false },
    { id: 3012, text: 'Implement inheritance from scratch', depth: 1, checked: false },
    { id: 3013, text: 'Polymorphism', depth: 0, checked: false },
    { id: 3014, text: 'Compile-time polymorphism', depth: 1, checked: false },
    { id: 3015, text: 'Runtime polymorphism', depth: 1, checked: false },
    { id: 3016, text: 'Dynamic method dispatch', depth: 1, checked: false },
    { id: 3017, text: 'Object Relationships', depth: 0, checked: false },
    { id: 3018, text: 'Association', depth: 1, checked: false },
    { id: 3019, text: 'Aggregation', depth: 1, checked: false },
    { id: 3020, text: 'Composition', depth: 1, checked: false },
    { id: 3021, text: 'Composition vs Inheritance', depth: 0, checked: false },
    { id: 3022, text: 'Implement same example using inheritance', depth: 1, checked: false },
    { id: 3023, text: 'Implement same example using composition', depth: 1, checked: false },
    { id: 3024, text: 'Compare trade-offs', depth: 1, checked: false },
    { id: 3025, text: 'Object Design Fundamentals', depth: 0, checked: false },
    { id: 3026, text: 'Identity vs state vs behavior', depth: 1, checked: false },
    { id: 3027, text: 'High cohesion', depth: 1, checked: false },
    { id: 3028, text: 'Low coupling', depth: 1, checked: false },
    { id: 3029, text: 'Immutability', depth: 0, checked: false },
    { id: 3030, text: 'Immutable objects', depth: 1, checked: false },
    { id: 3031, text: 'final keyword and immutability', depth: 1, checked: false },
    { id: 3032, text: 'Design an immutable class', depth: 1, checked: false },
    { id: 3033, text: 'Single Responsibility Principle', depth: 0, checked: false },
    { id: 3034, text: 'Identify SRP violation', depth: 1, checked: false },
    { id: 3035, text: 'Refactor bad code', depth: 1, checked: false },
    { id: 3036, text: 'Design responsibilities correctly', depth: 1, checked: false },
    { id: 3037, text: 'Dependency Injection', depth: 0, checked: false },
    { id: 3038, text: 'Constructor injection', depth: 1, checked: false },
    { id: 3039, text: 'Dependency vs implementation', depth: 1, checked: false },
    { id: 3040, text: 'Open/Closed Principle', depth: 0, checked: false },
    { id: 3041, text: 'Identify OCP violation', depth: 1, checked: false },
    { id: 3042, text: 'Refactor bad code', depth: 1, checked: false },
    { id: 3043, text: 'Design for extension', depth: 1, checked: false },
    { id: 3044, text: 'Liskov Substitution Principle', depth: 0, checked: false },
    { id: 3045, text: 'Identify LSP violation', depth: 1, checked: false },
    { id: 3046, text: 'Refactor bad code', depth: 1, checked: false },
    { id: 3047, text: 'Interface Segregation Principle', depth: 0, checked: false },
    { id: 3048, text: 'Identify ISP violation', depth: 1, checked: false },
    { id: 3049, text: 'Split large interfaces', depth: 1, checked: false },
    { id: 3050, text: 'Dependency Inversion Principle', depth: 0, checked: false },
    { id: 3051, text: 'Identify DIP violation', depth: 1, checked: false },
    { id: 3052, text: 'Depend on abstractions', depth: 1, checked: false },
    { id: 3053, text: 'Refactor bad code', depth: 1, checked: false },
  ]),
  G('Week 2 — Java Design Fundamentals + Design Patterns', [
    { id: 3054, text: 'Java Collections for LLD', depth: 0, checked: false },
    { id: 3055, text: 'List / Set / Map selection', depth: 1, checked: false },
    { id: 3056, text: 'HashMap internals relevant to LLD', depth: 1, checked: false },
    { id: 3057, text: 'Queue / Deque usage', depth: 1, checked: false },
    { id: 3058, text: 'equals() and hashCode()', depth: 0, checked: false },
    { id: 3059, text: 'Contract between equals and hashCode', depth: 1, checked: false },
    { id: 3060, text: 'Implement correctly for domain objects', depth: 1, checked: false },
    { id: 3061, text: 'Generics', depth: 0, checked: false },
    { id: 3062, text: 'Generic classes and methods', depth: 1, checked: false },
    { id: 3063, text: 'Bounded generics', depth: 1, checked: false },
    { id: 3064, text: 'Generics in reusable LLD components', depth: 1, checked: false },
    { id: 3065, text: 'Enums and Value Objects', depth: 0, checked: false },
    { id: 3066, text: 'Enums for domain states/types', depth: 1, checked: false },
    { id: 3067, text: 'Value object design', depth: 1, checked: false },
    { id: 3068, text: 'Exception and Error Design', depth: 0, checked: false },
    { id: 3069, text: 'Checked vs unchecked exceptions', depth: 1, checked: false },
    { id: 3070, text: 'Domain-specific exceptions', depth: 1, checked: false },
    { id: 3071, text: 'Failure handling in LLD', depth: 1, checked: false },
    { id: 3072, text: 'Interface Design', depth: 0, checked: false },
    { id: 3073, text: 'Small focused interfaces', depth: 1, checked: false },
    { id: 3074, text: 'Program to interfaces', depth: 1, checked: false },
    { id: 3075, text: 'Avoid unnecessary abstractions', depth: 1, checked: false },
    { id: 3076, text: 'Strategy Pattern', depth: 0, checked: false },
    { id: 3077, text: 'Payment methods — Card / UPI / Wallet', depth: 1, checked: false },
    { id: 3078, text: 'Add new strategy without modifying existing code', depth: 1, checked: false },
    { id: 3079, text: 'Identify when Strategy is appropriate', depth: 1, checked: false },
    { id: 3080, text: 'Factory Pattern', depth: 0, checked: false },
    { id: 3081, text: 'Multi-type entity creation', depth: 1, checked: false },
    { id: 3082, text: 'Factory vs direct object creation', depth: 1, checked: false },
    { id: 3083, text: 'Add a new entity type', depth: 1, checked: false },
    { id: 3084, text: 'Builder Pattern', depth: 0, checked: false },
    { id: 3085, text: 'Complex object construction', depth: 1, checked: false },
    { id: 3086, text: 'Optional parameters', depth: 1, checked: false },
    { id: 3087, text: 'Observer Pattern', depth: 0, checked: false },
    { id: 3088, text: 'Notification system', depth: 1, checked: false },
    { id: 3089, text: 'Observer registration/removal', depth: 1, checked: false },
    { id: 3090, text: 'Multiple observers', depth: 1, checked: false },
    { id: 3091, text: 'Decorator Pattern', depth: 0, checked: false },
    { id: 3092, text: 'Pizza / Coffee add-on pricing', depth: 1, checked: false },
    { id: 3093, text: 'Stack multiple decorators', depth: 1, checked: false },
    { id: 3094, text: 'Singleton Pattern', depth: 0, checked: false },
    { id: 3095, text: 'Configuration manager', depth: 1, checked: false },
    { id: 3096, text: 'Thread-safe Singleton', depth: 1, checked: false },
    { id: 3097, text: 'Singleton drawbacks', depth: 1, checked: false },
    { id: 3098, text: 'Pattern Review', depth: 0, checked: false },
    { id: 3099, text: 'Choose pattern from requirements', depth: 1, checked: false },
    { id: 3100, text: 'Implement one pattern from memory', depth: 1, checked: false },
    { id: 3101, text: 'Explain alternatives and trade-offs', depth: 1, checked: false },
  ]),
  G('Week 3 — LLD Core Problems', [
    { id: 3102, text: 'Parking Lot', depth: 0, checked: false },
    { id: 3103, text: 'Requirements gathering', depth: 1, checked: false },
    { id: 3104, text: 'Identify entities and responsibilities', depth: 1, checked: false },
    { id: 3105, text: 'Identify relationships', depth: 1, checked: false },
    { id: 3106, text: 'Class design', depth: 1, checked: false },
    { id: 3107, text: 'Interfaces and abstractions', depth: 1, checked: false },
    { id: 3108, text: 'Implement core classes', depth: 1, checked: false },
    { id: 3109, text: 'Complete implementation', depth: 1, checked: false },
    { id: 3110, text: 'Vehicle and parking spot types', depth: 1, checked: false },
    { id: 3111, text: 'Pricing / ticket handling', depth: 1, checked: false },
    { id: 3112, text: 'Vending Machine', depth: 0, checked: false },
    { id: 3113, text: 'Requirements', depth: 1, checked: false },
    { id: 3114, text: 'State identification', depth: 1, checked: false },
    { id: 3115, text: 'State transition design', depth: 1, checked: false },
    { id: 3116, text: 'State pattern implementation', depth: 1, checked: false },
    { id: 3117, text: 'Inventory management', depth: 1, checked: false },
    { id: 3118, text: 'Payment and refund handling', depth: 1, checked: false },
    { id: 3119, text: 'State Machines', depth: 0, checked: false },
    { id: 3120, text: 'Identify states and transitions', depth: 1, checked: false },
    { id: 3121, text: 'Model invalid transitions', depth: 1, checked: false },
    { id: 3122, text: 'Elevator System', depth: 0, checked: false },
    { id: 3123, text: 'Requirements and constraints', depth: 1, checked: false },
    { id: 3124, text: 'Identify entities', depth: 1, checked: false },
    { id: 3125, text: 'Define elevator states', depth: 1, checked: false },
    { id: 3126, text: 'Class design', depth: 1, checked: false },
    { id: 3127, text: 'Request scheduling', depth: 1, checked: false },
    { id: 3128, text: 'Handle concurrent requests and edge cases', depth: 1, checked: false },
  ]),
  G('Week 4 — Advanced LLD + Interview Practice', [
    { id: 3129, text: 'LRU Cache', depth: 0, checked: false },
    { id: 3130, text: 'Requirements', depth: 1, checked: false },
    { id: 3131, text: 'Identify required data structures', depth: 1, checked: false },
    { id: 3132, text: 'Design class structure', depth: 1, checked: false },
    { id: 3133, text: 'Data Structure Design', depth: 0, checked: false },
    { id: 3134, text: 'HashMap + Doubly Linked List', depth: 1, checked: false },
    { id: 3135, text: 'Maintain O(1) get and put', depth: 1, checked: false },
    { id: 3136, text: 'Complete implementation', depth: 1, checked: false },
    { id: 3137, text: 'Eviction logic', depth: 1, checked: false },
    { id: 3138, text: 'Edge-case testing', depth: 1, checked: false },
    { id: 3139, text: 'Thread Safety', depth: 0, checked: false },
    { id: 3140, text: 'Identify shared mutable state', depth: 1, checked: false },
    { id: 3141, text: 'Design thread-safe cache access', depth: 1, checked: false },
    { id: 3142, text: 'Rate Limiter', depth: 0, checked: false },
    { id: 3143, text: 'Requirements and constraints', depth: 1, checked: false },
    { id: 3144, text: 'Token Bucket design', depth: 1, checked: false },
    { id: 3145, text: 'Token Bucket implementation', depth: 1, checked: false },
    { id: 3146, text: 'Sliding Window design', depth: 1, checked: false },
    { id: 3147, text: 'Sliding Window implementation', depth: 1, checked: false },
    { id: 3148, text: 'Compare Token Bucket vs Sliding Window', depth: 1, checked: false },
    { id: 3149, text: 'Concurrency Fundamentals', depth: 0, checked: false },
    { id: 3150, text: 'Race conditions', depth: 1, checked: false },
    { id: 3151, text: 'synchronized / locks', depth: 1, checked: false },
    { id: 3152, text: 'Atomic operations', depth: 1, checked: false },
    { id: 3153, text: 'Splitwise', depth: 0, checked: false },
    { id: 3154, text: 'Requirements', depth: 1, checked: false },
    { id: 3155, text: 'Identify entities and relationships', depth: 1, checked: false },
    { id: 3156, text: 'Design expense splitting model', depth: 1, checked: false },
    { id: 3157, text: 'Domain Modeling', depth: 0, checked: false },
    { id: 3158, text: 'Expense / User / Group / Balance', depth: 1, checked: false },
    { id: 3159, text: 'Different split strategies', depth: 1, checked: false },
    { id: 3160, text: 'Implement core functionality', depth: 1, checked: false },
    { id: 3161, text: 'Implement settlement', depth: 1, checked: false },
    { id: 3162, text: 'Handle equal / exact / percentage splits', depth: 1, checked: false },
    { id: 3163, text: 'Extensibility', depth: 0, checked: false },
    { id: 3164, text: 'Add new split strategy', depth: 1, checked: false },
    { id: 3165, text: 'Apply Strategy appropriately', depth: 1, checked: false },
    { id: 3166, text: 'Identify SOLID principles used', depth: 1, checked: false },
    { id: 3167, text: 'BookMyShow', depth: 0, checked: false },
    { id: 3168, text: 'Cold requirements gathering', depth: 1, checked: false },
    { id: 3169, text: 'Identify entities and relationships', depth: 1, checked: false },
    { id: 3170, text: 'Design class structure', depth: 1, checked: false },
    { id: 3171, text: 'Interview Simulation', depth: 0, checked: false },
    { id: 3172, text: 'Design without preparation', depth: 1, checked: false },
    { id: 3173, text: 'Explain design decisions', depth: 1, checked: false },
    { id: 3174, text: 'Discuss scalability and concurrency concerns', depth: 1, checked: false },
    { id: 3175, text: 'Handle interviewer change requests', depth: 1, checked: false },
    { id: 3176, text: 'Final Review', depth: 0, checked: false },
    { id: 3177, text: 'OOP fundamentals', depth: 1, checked: false },
    { id: 3178, text: 'SOLID principles', depth: 1, checked: false },
    { id: 3179, text: 'Design patterns', depth: 1, checked: false },
    { id: 3180, text: 'LLD problem-solving approach', depth: 1, checked: false },
  ]),
];

export default groups;
