import { ChecklistGroup } from './system-design-checklist';

const G = (title: string, items: { id: number; text: string; depth: number; checked: boolean }[]): ChecklistGroup => ({ title, items });

const groups: ChecklistGroup[] = [
  G('Databases', [
    { id: 2001, text: 'Relational Databases', depth: 0, checked: true },
    { id: 2002, text: 'B+ Tree Indexing', depth: 0, checked: true },
    { id: 2003, text: 'Understand node structure (internal vs leaf nodes)', depth: 1, checked: true },
    { id: 2004, text: 'Understand branching factor', depth: 1, checked: true },
    { id: 2005, text: 'Understand disk I/O reduction logic', depth: 1, checked: true },
    { id: 2006, text: 'Clustered vs Non-Clustered Index', depth: 0, checked: true },
    { id: 2007, text: 'Storage layout difference', depth: 1, checked: true },
    { id: 2008, text: 'Performance implications', depth: 1, checked: true },
    { id: 2009, text: 'Covering Index', depth: 0, checked: true },
    { id: 2010, text: 'Understand index-only scan', depth: 1, checked: true },
    { id: 2011, text: 'When it avoids table lookup', depth: 1, checked: true },
    { id: 2012, text: 'Query Execution Plan', depth: 0, checked: true },
    { id: 2013, text: 'Read EXPLAIN output', depth: 1, checked: true },
    { id: 2014, text: 'Identify full table scan', depth: 1, checked: true },
    { id: 2015, text: 'Identify index scan', depth: 1, checked: true },
    { id: 2016, text: 'Write-Ahead Logging (WAL)', depth: 0, checked: true },
    { id: 2017, text: 'Understand log-first write principle', depth: 1, checked: true },
    { id: 2018, text: 'Crash recovery flow', depth: 1, checked: true },
    { id: 2019, text: 'Checkpointing', depth: 0, checked: true },
    { id: 2020, text: 'Why checkpoints exist', depth: 1, checked: true },
    { id: 2021, text: 'Trade-off between frequency & performance', depth: 1, checked: true },
    { id: 2022, text: 'ACID (Implementation Level)', depth: 0, checked: true },
    { id: 2023, text: 'Atomicity via WAL', depth: 1, checked: true },
    { id: 2024, text: 'Consistency via constraints', depth: 1, checked: true },
    { id: 2025, text: 'Isolation via locking/MVCC', depth: 1, checked: true },
    { id: 2026, text: 'Durability via fsync', depth: 1, checked: true },
    { id: 2027, text: 'Locking vs MVCC', depth: 0, checked: true },
    { id: 2028, text: 'Read/write blocking behavior', depth: 1, checked: true },
    { id: 2029, text: 'Snapshot visibility', depth: 1, checked: true },
    { id: 2030, text: 'Isolation Levels', depth: 0, checked: true },
    { id: 2031, text: 'Dirty Read', depth: 1, checked: true },
    { id: 2032, text: 'Non-Repeatable Read', depth: 1, checked: true },
    { id: 2033, text: 'Phantom Read', depth: 1, checked: true },
    { id: 2034, text: 'MVCC Mechanics', depth: 0, checked: true },
    { id: 2035, text: 'Version chains', depth: 1, checked: true },
    { id: 2036, text: 'Snapshot creation', depth: 1, checked: true },
    { id: 2037, text: 'Snapshot Isolation', depth: 1, checked: true },
    { id: 2038, text: 'Repeatable Read vs Serializable', depth: 1, checked: true },
    { id: 2039, text: 'Write Skew Problem', depth: 1, checked: true },
    { id: 2040, text: 'Replication', depth: 0, checked: true },
    { id: 2041, text: 'Leader-Follower Architecture', depth: 1, checked: true },
    { id: 2042, text: 'Sync vs Async Replication', depth: 1, checked: true },
    { id: 2043, text: 'Replication Lag', depth: 1, checked: true },
    { id: 2044, text: 'Read-After-Write Consistency', depth: 1, checked: true },
    { id: 2045, text: 'Failover Process', depth: 1, checked: true },
    { id: 2046, text: 'Scaling Databases', depth: 0, checked: true },
    { id: 2047, text: 'Vertical Scaling', depth: 1, checked: true },
    { id: 2048, text: 'Horizontal Scaling', depth: 1, checked: true },
    { id: 2049, text: 'Read Replica Limits', depth: 1, checked: true },
    { id: 2050, text: 'Write Bottleneck', depth: 1, checked: true },
    { id: 2051, text: 'Cross-Region Replication Trade-offs', depth: 1, checked: true },
    { id: 2052, text: 'Strong vs Eventual Consistency', depth: 1, checked: true },
    { id: 2053, text: 'Sharding / Partitioning', depth: 1, checked: true },
    { id: 2054, text: 'Range-Based Sharding', depth: 2, checked: true },
    { id: 2055, text: 'Hash-Based Sharding', depth: 2, checked: true },
    { id: 2056, text: 'Directory-Based Sharding', depth: 2, checked: true },
    { id: 2057, text: 'Consistent Hashing', depth: 2, checked: true },
    { id: 2058, text: 'Rebalancing Strategy', depth: 2, checked: true },
    { id: 2059, text: 'Hot Partition Issue', depth: 2, checked: true },
    { id: 2060, text: 'Cross-Shard Joins', depth: 2, checked: true },
    { id: 2061, text: 'Global Secondary Indexes', depth: 2, checked: true },
    { id: 2062, text: 'NoSQL', depth: 0, checked: true },
    { id: 2063, text: 'Key-Value Stores', depth: 1, checked: true },
    { id: 2064, text: 'Document Databases', depth: 1, checked: true },
    { id: 2065, text: 'Column Stores', depth: 1, checked: true },
    { id: 2066, text: 'Graph Databases', depth: 1, checked: true },
    { id: 2067, text: 'When to Prefer Each', depth: 1, checked: true },
    { id: 2068, text: 'Denormalization Trade-offs', depth: 1, checked: true },
    { id: 2069, text: 'Eventual Consistency Behavior', depth: 1, checked: true },
    { id: 2070, text: 'Secondary Index Limitations', depth: 1, checked: true },
    { id: 2071, text: 'Multi-Leader Conflicts', depth: 0, checked: true },
    { id: 2072, text: 'Split Brain', depth: 0, checked: true },
  ]),
  G('Caching', [
    { id: 2073, text: 'Core Patterns', depth: 0, checked: true },
    { id: 2074, text: 'Cache-Aside', depth: 1, checked: true },
    { id: 2075, text: 'Write-Through', depth: 2, checked: true },
    { id: 2076, text: 'Write-Back', depth: 1, checked: true },
    { id: 2077, text: 'Write-Around', depth: 1, checked: true },
    { id: 2078, text: 'Cache Warming', depth: 1, checked: true },
    { id: 2079, text: 'TTL Strategy Design', depth: 1, checked: true },
    { id: 2080, text: 'Eviction Policies', depth: 0, checked: true },
    { id: 2081, text: 'LRU', depth: 1, checked: true },
    { id: 2082, text: 'LFU', depth: 1, checked: true },
    { id: 2083, text: 'FIFO', depth: 1, checked: true },
    { id: 2084, text: 'Random Eviction', depth: 1, checked: true },
    { id: 2085, text: 'Memory Fragmentation (Internal vs External)', depth: 1, checked: true },
    { id: 2086, text: 'Consistency', depth: 0, checked: false },
    { id: 2087, text: 'Cache Invalidation Strategies', depth: 1, checked: true },
    { id: 2088, text: 'Double Delete Pattern', depth: 1, checked: false },
    { id: 2089, text: 'Stale Data Window', depth: 1, checked: false },
    { id: 2090, text: 'Read-After-Write Inconsistency', depth: 1, checked: false },
    { id: 2091, text: 'Failure Scenarios', depth: 0, checked: false },
    { id: 2092, text: 'Cache Stampede', depth: 1, checked: false },
    { id: 2093, text: 'Thundering Herd', depth: 1, checked: false },
    { id: 2094, text: 'Hot Key Problem', depth: 1, checked: false },
    { id: 2095, text: 'Cache Penetration', depth: 1, checked: false },
    { id: 2096, text: 'Cold Start Problem', depth: 1, checked: false },
    { id: 2097, text: 'Redis Internals', depth: 0, checked: false },
    { id: 2098, text: 'Single-Threaded Event Loop', depth: 1, checked: false },
    { id: 2099, text: 'Why Redis Is Fast', depth: 1, checked: false },
    { id: 2100, text: 'RDB Persistence', depth: 1, checked: false },
    { id: 2101, text: 'AOF Persistence', depth: 1, checked: false },
    { id: 2102, text: 'Replication Model', depth: 1, checked: false },
    { id: 2103, text: 'Sentinel', depth: 1, checked: false },
    { id: 2104, text: 'Cluster Mode', depth: 1, checked: false },
    { id: 2105, text: 'Slot-Based Sharding', depth: 1, checked: false },
  ]),
  G('Async Processing', [
    { id: 2106, text: 'Messaging Fundamentals', depth: 0, checked: false },
    { id: 2107, text: 'At-Most-Once', depth: 1, checked: false },
    { id: 2108, text: 'At-Least-Once', depth: 1, checked: false },
    { id: 2109, text: 'Exactly-Once (Practical Meaning)', depth: 1, checked: false },
    { id: 2110, text: 'Idempotency', depth: 1, checked: false },
    { id: 2111, text: 'Dead Letter Queue', depth: 1, checked: false },
    { id: 2112, text: 'Retry Strategies', depth: 1, checked: false },
    { id: 2113, text: 'Backpressure Handling', depth: 1, checked: false },
    { id: 2114, text: 'Kafka Internals', depth: 0, checked: false },
    { id: 2115, text: 'Topic Architecture', depth: 1, checked: false },
    { id: 2116, text: 'Partition Strategy', depth: 1, checked: false },
    { id: 2117, text: 'Partition Key Selection', depth: 1, checked: false },
    { id: 2118, text: 'Ordering Guarantees', depth: 1, checked: false },
    { id: 2119, text: 'Offset Management', depth: 1, checked: false },
    { id: 2120, text: 'Consumer Groups', depth: 1, checked: false },
    { id: 2121, text: 'Rebalancing Process', depth: 1, checked: false },
    { id: 2122, text: 'ISR (In-Sync Replicas)', depth: 1, checked: false },
    { id: 2123, text: 'Leader Election', depth: 1, checked: false },
    { id: 2124, text: 'Retention Policies', depth: 1, checked: false },
    { id: 2125, text: 'Log Compaction', depth: 1, checked: false },
    { id: 2126, text: 'Pull Model Rationale', depth: 1, checked: false },
    { id: 2127, text: 'Failure Modes', depth: 0, checked: false },
    { id: 2128, text: 'Producer Retry Duplication', depth: 1, checked: false },
    { id: 2129, text: 'Consumer Crash Mid-Processing', depth: 1, checked: false },
    { id: 2130, text: 'Broker Failure', depth: 1, checked: false },
    { id: 2131, text: 'Network Partition', depth: 1, checked: false },
    { id: 2132, text: 'Data Loss Scenarios', depth: 1, checked: false },
  ]),
  G('Load Balancing & Resiliency', [
    { id: 2133, text: 'Load Balancers', depth: 0, checked: false },
    { id: 2134, text: 'L4 vs L7', depth: 1, checked: false },
    { id: 2135, text: 'Round Robin', depth: 1, checked: false },
    { id: 2136, text: 'Least Connections', depth: 1, checked: false },
    { id: 2137, text: 'Consistent Hashing', depth: 1, checked: false },
    { id: 2138, text: 'Health Checks', depth: 1, checked: false },
    { id: 2139, text: 'Sticky Sessions', depth: 1, checked: false },
    { id: 2140, text: 'Circuit Breaker', depth: 0, checked: false },
    { id: 2141, text: 'Closed State', depth: 1, checked: false },
    { id: 2142, text: 'Open State', depth: 1, checked: false },
    { id: 2143, text: 'Half-Open State', depth: 1, checked: false },
    { id: 2144, text: 'Fail Fast Principle', depth: 0, checked: false },
    { id: 2145, text: 'Cascading Failure Prevention', depth: 0, checked: false },
    { id: 2146, text: 'Leader Election', depth: 0, checked: false },
    { id: 2147, text: 'Quorum Concept', depth: 0, checked: false },
    { id: 2148, text: 'Raft Basics', depth: 0, checked: false },
    { id: 2149, text: 'Heartbeats', depth: 1, checked: false },
    { id: 2150, text: 'Majority Consensus Logic', depth: 1, checked: false },
  ]),
  G('Estimation Practice', [
    { id: 2151, text: 'QPS Estimation', depth: 0, checked: false },
    { id: 2152, text: 'Storage Estimation', depth: 0, checked: false },
    { id: 2153, text: 'Bandwidth Estimation', depth: 0, checked: false },
    { id: 2154, text: 'Peak vs Average Traffic', depth: 0, checked: false },
    { id: 2155, text: 'Read/Write Ratio Impact', depth: 0, checked: false },
    { id: 2156, text: '2-Minute Estimation Drill', depth: 0, checked: false },
  ]),
  G('API Design Principles', [
    { id: 2157, text: 'When to use (gRPC vs REST)', depth: 0, checked: false },
    { id: 2158, text: 'Protobuf advantages', depth: 0, checked: false },
    { id: 2159, text: 'REST best practices', depth: 0, checked: false },
    { id: 2160, text: 'Stateless', depth: 1, checked: false },
    { id: 2161, text: 'Uniform interface', depth: 1, checked: false },
    { id: 2162, text: 'HATEOAS', depth: 1, checked: false },
    { id: 2163, text: 'GraphQL vs REST', depth: 0, checked: false },
    { id: 2164, text: 'Over-fetching vs under-fetching', depth: 1, checked: false },
    { id: 2165, text: 'Versioning strategies', depth: 0, checked: false },
    { id: 2166, text: 'URL versioning', depth: 1, checked: false },
    { id: 2167, text: 'Header-based versioning', depth: 1, checked: false },
    { id: 2168, text: 'Query parameter versioning', depth: 1, checked: false },
    { id: 2169, text: 'Idempotency', depth: 0, checked: false },
    { id: 2170, text: 'Idempotency-Key header', depth: 1, checked: false },
    { id: 2171, text: 'Pagination', depth: 0, checked: false },
    { id: 2172, text: 'Offset-based pagination', depth: 1, checked: false },
    { id: 2173, text: 'Cursor-based pagination', depth: 1, checked: false },
    { id: 2174, text: 'Sorting & Filtering best practices', depth: 0, checked: false },
    { id: 2175, text: 'Server-side sorting', depth: 1, checked: false },
    { id: 2176, text: 'Multi-field sorting', depth: 1, checked: false },
    { id: 2177, text: 'Filtering with query params', depth: 1, checked: false },
    { id: 2178, text: 'Index optimization', depth: 1, checked: false },
    { id: 2179, text: 'Avoid over-fetching', depth: 1, checked: false },
  ]),
  G('DNS & Traffic Routing', [
    { id: 2180, text: 'DNS Resolution Flow', depth: 0, checked: false },
    { id: 2181, text: 'Recursive vs Iterative Resolution', depth: 1, checked: false },
    { id: 2182, text: 'Root → TLD → Authoritative flow', depth: 1, checked: false },
    { id: 2183, text: 'Role of DNS Resolver', depth: 1, checked: false },
    { id: 2184, text: 'DNS Caching Layers', depth: 0, checked: false },
    { id: 2185, text: 'Browser Cache', depth: 1, checked: false },
    { id: 2186, text: 'OS Cache', depth: 1, checked: false },
    { id: 2187, text: 'ISP Resolver Cache', depth: 1, checked: false },
    { id: 2188, text: 'TTL impact on freshness', depth: 1, checked: false },
    { id: 2189, text: 'Geo-based Routing', depth: 0, checked: false },
    { id: 2190, text: 'Latency-based routing', depth: 1, checked: false },
    { id: 2191, text: 'Geo DNS vs Anycast', depth: 1, checked: false },
    { id: 2192, text: 'DNS Load Balancing', depth: 0, checked: false },
    { id: 2193, text: 'Round Robin DNS', depth: 1, checked: false },
    { id: 2194, text: 'Health check limitations', depth: 1, checked: false },
    { id: 2195, text: 'Failover challenges', depth: 1, checked: false },
  ]),
  G('CDN', [
    { id: 2196, text: 'CDN Architecture', depth: 0, checked: false },
    { id: 2197, text: 'Global edge network', depth: 1, checked: false },
    { id: 2198, text: 'Cache hierarchy', depth: 1, checked: false },
    { id: 2199, text: 'Edge vs Origin', depth: 0, checked: false },
    { id: 2200, text: 'Cache hit vs miss flow', depth: 1, checked: false },
    { id: 2201, text: 'Origin shielding', depth: 1, checked: false },
    { id: 2202, text: 'Push vs Pull CDN', depth: 0, checked: false },
    { id: 2203, text: 'Preload vs On-demand caching', depth: 1, checked: false },
    { id: 2204, text: 'Cache Strategies', depth: 0, checked: false },
    { id: 2205, text: 'Static vs Dynamic content caching', depth: 1, checked: false },
    { id: 2206, text: 'TTL tuning', depth: 1, checked: false },
    { id: 2207, text: 'Cache invalidation', depth: 1, checked: false },
    { id: 2208, text: 'Performance Optimization', depth: 0, checked: false },
    { id: 2209, text: 'Latency reduction', depth: 1, checked: false },
    { id: 2210, text: 'Bandwidth savings', depth: 1, checked: false },
  ]),
  G('Proxies', [
    { id: 2211, text: 'Forward Proxy', depth: 0, checked: false },
    { id: 2212, text: 'Client-side proxying', depth: 1, checked: false },
    { id: 2213, text: 'Use cases (privacy, filtering)', depth: 1, checked: false },
    { id: 2214, text: 'Reverse Proxy', depth: 0, checked: false },
    { id: 2215, text: 'Server-side proxying', depth: 1, checked: false },
    { id: 2216, text: 'Load distribution', depth: 1, checked: false },
    { id: 2217, text: 'Proxy vs Load Balancer', depth: 0, checked: false },
    { id: 2218, text: 'L7 overlap', depth: 1, checked: false },
    { id: 2219, text: 'Routing vs distribution', depth: 1, checked: false },
    { id: 2220, text: 'VPN vs Proxy', depth: 0, checked: false },
    { id: 2221, text: 'Encryption differences', depth: 1, checked: false },
    { id: 2222, text: 'Network-level vs app-level', depth: 1, checked: false },
  ]),
  G('Core Distributed System Characteristics', [
    { id: 2223, text: 'Scalability', depth: 0, checked: false },
    { id: 2224, text: 'Horizontal scaling patterns', depth: 1, checked: false },
    { id: 2225, text: 'Auto-scaling triggers', depth: 1, checked: false },
    { id: 2226, text: 'Availability', depth: 0, checked: false },
    { id: 2227, text: 'SLA / SLO basics', depth: 1, checked: false },
    { id: 2228, text: 'Downtime impact', depth: 1, checked: false },
    { id: 2229, text: 'Latency vs Throughput', depth: 0, checked: false },
    { id: 2230, text: 'Tail latency (P99)', depth: 1, checked: false },
    { id: 2231, text: 'Tradeoffs', depth: 1, checked: false },
    { id: 2232, text: 'Concurrency & Coordination', depth: 0, checked: false },
    { id: 2233, text: 'Locks vs lock-free systems', depth: 1, checked: false },
    { id: 2234, text: 'Distributed coordination basics', depth: 1, checked: false },
    { id: 2235, text: 'Observability', depth: 0, checked: false },
    { id: 2236, text: 'Metrics (CPU, memory, QPS)', depth: 1, checked: false },
    { id: 2237, text: 'Logging', depth: 1, checked: false },
    { id: 2238, text: 'Tracing', depth: 1, checked: false },
    { id: 2239, text: 'Resilience & Error Handling', depth: 0, checked: false },
    { id: 2240, text: 'Retry storms', depth: 1, checked: false },
    { id: 2241, text: 'Backoff strategies', depth: 1, checked: false },
    { id: 2242, text: 'Fault Tolerance', depth: 0, checked: false },
    { id: 2243, text: 'Redundancy strategies', depth: 1, checked: false },
    { id: 2244, text: 'Failover mechanisms', depth: 1, checked: false },
  ]),
  G('Network Essentials', [
    { id: 2245, text: 'HTTP vs HTTPS', depth: 0, checked: false },
    { id: 2246, text: 'TLS handshake basics', depth: 1, checked: false },
    { id: 2247, text: 'Certificate validation', depth: 1, checked: false },
    { id: 2248, text: 'Encryption overhead vs security benefits', depth: 1, checked: false },
    { id: 2249, text: 'TCP vs UDP', depth: 0, checked: false },
    { id: 2250, text: 'Connection-oriented vs connectionless', depth: 1, checked: false },
    { id: 2251, text: 'Reliability (retransmission, ordering)', depth: 1, checked: false },
    { id: 2252, text: 'Use cases (APIs vs streaming/gaming)', depth: 1, checked: false },
    { id: 2253, text: 'HTTP Versions', depth: 0, checked: false },
    { id: 2254, text: 'HTTP/1.1: Head-of-line blocking', depth: 1, checked: false },
    { id: 2255, text: 'HTTP/1.1: Keep-alive connections', depth: 1, checked: false },
    { id: 2256, text: 'HTTP/2: Multiplexing', depth: 1, checked: false },
    { id: 2257, text: 'HTTP/2: Header compression (HPACK)', depth: 1, checked: false },
    { id: 2258, text: 'HTTP/3: QUIC over UDP', depth: 1, checked: false },
    { id: 2259, text: 'HTTP/3: Reduced latency (0-RTT)', depth: 1, checked: false },
    { id: 2260, text: 'URL vs URI vs URN', depth: 0, checked: false },
    { id: 2261, text: 'URI as identifier', depth: 1, checked: false },
    { id: 2262, text: 'URL as locator', depth: 1, checked: false },
    { id: 2263, text: 'URN as name-based identifier', depth: 1, checked: false },
  ]),
  G('Data Integrity & System Signals', [
    { id: 2264, text: 'Checksum', depth: 0, checked: false },
    { id: 2265, text: 'Data integrity verification', depth: 1, checked: false },
    { id: 2266, text: 'Corruption detection', depth: 1, checked: false },
    { id: 2267, text: 'Heartbeat Mechanism', depth: 0, checked: false },
    { id: 2268, text: 'Node liveness detection', depth: 1, checked: false },
    { id: 2269, text: 'Failure detection timing', depth: 1, checked: false },
    { id: 2270, text: 'Leader–Follower Pattern', depth: 0, checked: false },
    { id: 2271, text: 'Write leader', depth: 1, checked: false },
    { id: 2272, text: 'Read replicas', depth: 1, checked: false },
    { id: 2273, text: 'Failover switching', depth: 1, checked: false },
    { id: 2274, text: 'Quorum Concept', depth: 0, checked: false },
    { id: 2275, text: 'Read quorum (R)', depth: 1, checked: false },
    { id: 2276, text: 'Write quorum (W)', depth: 1, checked: false },
    { id: 2277, text: 'R + W > N rule', depth: 1, checked: false },
  ]),
  G('Security', [
    { id: 2278, text: 'Authentication', depth: 0, checked: false },
    { id: 2279, text: 'Session-based auth', depth: 1, checked: false },
    { id: 2280, text: 'Token-based auth', depth: 1, checked: false },
    { id: 2281, text: 'Authorization', depth: 0, checked: false },
    { id: 2282, text: 'RBAC', depth: 1, checked: false },
    { id: 2283, text: 'ABAC', depth: 1, checked: false },
    { id: 2284, text: 'OAuth vs JWT', depth: 0, checked: false },
    { id: 2285, text: 'Token flow', depth: 1, checked: false },
    { id: 2286, text: 'Stateless authentication', depth: 1, checked: false },
    { id: 2287, text: 'Encryption', depth: 0, checked: false },
    { id: 2288, text: 'At rest', depth: 1, checked: false },
    { id: 2289, text: 'In transit (TLS)', depth: 1, checked: false },
    { id: 2290, text: 'DDoS Protection', depth: 0, checked: false },
    { id: 2291, text: 'Rate limiting', depth: 1, checked: false },
    { id: 2292, text: 'Traffic filtering', depth: 1, checked: false },
    { id: 2293, text: 'CDN protection', depth: 1, checked: false },
  ]),
  G('Distributed File Systems', [
    { id: 2294, text: 'DFS Architecture', depth: 0, checked: false },
    { id: 2295, text: 'Master node', depth: 1, checked: false },
    { id: 2296, text: 'Worker nodes', depth: 1, checked: false },
    { id: 2297, text: 'Storage Model', depth: 0, checked: false },
    { id: 2298, text: 'Block-based storage', depth: 1, checked: false },
    { id: 2299, text: 'File chunking', depth: 1, checked: false },
    { id: 2300, text: 'Replication', depth: 0, checked: false },
    { id: 2301, text: 'Multi-node redundancy', depth: 1, checked: false },
    { id: 2302, text: 'Data consistency', depth: 1, checked: false },
    { id: 2303, text: 'Fault Handling', depth: 0, checked: false },
    { id: 2304, text: 'Node failure recovery', depth: 1, checked: false },
    { id: 2305, text: 'Re-replication mechanisms', depth: 1, checked: false },
  ]),
  G('Bloom Filters', [
    { id: 2306, text: 'Core Concept', depth: 0, checked: false },
    { id: 2307, text: 'Probabilistic membership check', depth: 1, checked: false },
    { id: 2308, text: 'Internal Working', depth: 0, checked: false },
    { id: 2309, text: 'Hash functions', depth: 1, checked: false },
    { id: 2310, text: 'Bit array mapping', depth: 1, checked: false },
    { id: 2311, text: 'Tradeoffs', depth: 0, checked: false },
    { id: 2312, text: 'False positives', depth: 1, checked: false },
    { id: 2313, text: 'No false negatives', depth: 1, checked: false },
    { id: 2314, text: 'Use Cases', depth: 0, checked: false },
    { id: 2315, text: 'Cache filtering', depth: 1, checked: false },
    { id: 2316, text: 'Database query optimization', depth: 1, checked: false },
  ]),
  G('Real-Time Communication', [
    { id: 2317, text: 'Long Polling', depth: 0, checked: false },
    { id: 2318, text: 'Client waits for response', depth: 1, checked: false },
    { id: 2319, text: 'WebSockets', depth: 0, checked: false },
    { id: 2320, text: 'Full-duplex communication', depth: 1, checked: false },
    { id: 2321, text: 'Server-Sent Events (SSE)', depth: 0, checked: false },
    { id: 2322, text: 'One-way streaming', depth: 1, checked: false },
    { id: 2323, text: 'Tradeoffs', depth: 0, checked: false },
    { id: 2324, text: 'Scalability vs latency', depth: 1, checked: false },
  ]),
  G('System Design Tradeoffs', [
    { id: 2325, text: 'CAP Theorem', depth: 0, checked: false },
    { id: 2326, text: 'Consistency vs Availability', depth: 1, checked: false },
    { id: 2327, text: 'Partition tolerance', depth: 1, checked: false },
    { id: 2328, text: 'PACELC Theorem', depth: 0, checked: false },
    { id: 2329, text: 'Latency vs Consistency tradeoff', depth: 1, checked: false },
    { id: 2330, text: 'Real-world Tradeoffs', depth: 0, checked: false },
    { id: 2331, text: 'Strong vs Eventual consistency', depth: 1, checked: false },
    { id: 2332, text: 'Cost vs performance', depth: 1, checked: false },
    { id: 2333, text: 'Simplicity vs scalability', depth: 1, checked: false },
  ]),
];

export default groups;
